#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
ip=$3
fork=$4
port=$5

app=sickbeard
user=sickbeard
install_dir=/opt/yunohost/$app

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Check port availability
sudo yunohost app checkport $port
if [[ ! $? -eq 0 ]]; then
      exit 1
  fi
  
# Copy of app for localhost installation
if [[ $ip == "127.0.0.1" ]]; then
	# The Python module Cheetah is required
	sudo apt-get install python-cheetah
	
	# Install the latest version of Sickbeard-Manager using the fork
	sudo mkdir -p $install_dir
	sudo git clone https://github.com/SiCKRAGETV/SickRage $install_dir
	#sudo git clone $fork $install_dir

    # Create sickbeard user
	sudo groupadd $user
	sudo useradd -d $install_dir -g $user -s /bin/false $user
	sudo chown -R $user:$user $install_dir
	
	# Init
	sudo cp -a ../conf/$app /etc/init.d/
	sudo chown root:root /etc/init.d/$app
	sudo chmod +x /etc/init.d/$app
	
	#sudo sed -i "s@PATHTOCHANGE@$path@g" /etc/init.d/$app
	#sudo sed -i "s@PORT@$port@g" /etc/init.d/$app
	sudo sed -i "s@INSTALLDIR@$install_dir@g" ../conf/sickrage.settings 
	sudo cp -a ../conf/sickrage.settings /etc/default/sickrage
	
	# Start App in order to create conf files
	sudo /etc/init.d/$app start
	sleep 10
	sudo /etc/init.d/$app stop
		
	# Sickbeard Conf files
	#sed -i "s@PATHTOCHANGE@$path@g" ../conf/config.ini
	#sed -i "s@PORT@$port@g" ../conf/config.ini
	#sudo cp ../conf/config.ini $install_dir/config.ini
fi

# Configure Nginx 
sudo sed -i "s@IPTOCHANGE@$ip@g" ../conf/nginx.conf
sudo sed -i "s@PORT@$port@g" ../conf/nginx.conf
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Add service to YunoHost's monitoring
sudo yunohost service add $app --log /var/log/$app/ --status "ps aux | grep $app | grep -v grep"

# Start $app service at boot
sudo update-rc.d $app defaults

# Reload $app, Nginx and regenerate SSOwat conf
sudo service $app start
sudo service nginx reload
sudo yunohost app ssowatconf